services:
  db:
    image: postgres:16-alpine
    container_name: data-fill-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: data-fill-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123456
    depends_on:
      - db
    volumes:
      - ./uploads:/data/upload

volumes:
  pgdata:
